### PR TITLE
Ported fmt.Errorf() -> fmt.Println()

### LINKED ISSUE #13: Unused returns from `fmt.Errorf()` across entire project
## Description
Throughout the project there are instances of `fmt.Errorf` being used but the result is not being called anywhere. All such functions can follow a better pattern where a default `error` type can be a return.

## Screenshot

image

### PR DESCRIPTION
**Pull request by IAmRiteshKoushik**
# Change Log

- Removes all `fmt.Errorf` in favour of `fmt.Println` (better fix needed)
- Formats the entire repository with `go fmt`

This PR completes issue #6 

Please review and merge @Ashrockzzz2003 @Abhinav-ark

### CODE REVIEW

**Review by Ashrockzzz2003 — CHANGES_REQUESTED** [review]
While we now actually are making use of those lines. It now raises a new problem.


## The problem

Consider the case where the user did not use Amrita VPN and an error is thrown. What happens is:

`Execute()` -> `start()` -> `getCoursesReq()` -> `fetchHTML()`

In `fetchHTML()`

https://github.com/CSE-25/amrita_pyq/blob/0b8264e5354474ea1d97c800b2ecde5b11d48df4/cmd/helpers.go#L16
This line prints the error first.

But we're also carrying the `err` string from `fetchHTML` back all the way to `start()` and printing it.

Now in the output: - TWO ERROR messages but in reverse order.

```
Error fetching the URL. Make sure you're connected to Amrita WiFi or VPN.
failed to fetch the HTML content
```

This doesn't look good to me. If we can give a cause and effect relationship to this and print properly, it will be useful.
Else, we can just ignore this error message.

Or have a logger that separates `debug` and `info` level error messages to make better use of the logs.

What's your take on this @IAmRiteshKoushik and @Abhinav-ark?

**Comment by IAmRiteshKoushik** [comment]
@Ashrockzzz2003 if we are porting the application to a TUI then we can have a `diagnostics box` on the right hand side of the screen where things can be monitored constantly and error messages / success messages can be printed. 

It can keep track of all events that are happening within the application and give visual updates to the user. (think of it as being similar to the chat section of a multiplayer gaming lobby - PLAYER JOINED, PLAYED LEFT, etc.)

**Comment by Abhinav-ark** [comment]
@Ashrockzzz2003 @IAmRiteshKoushik ErrorF was used because I wanted the application to stop in case of Errors.

**Comment by Abhinav-ark** [comment]
> While we now actually are making use of those lines. It now raises a new problem.
> 
> ## The problem
> Consider the case where the user did not use Amrita VPN and an error is thrown. What happens is:
> 
> `Execute()` -> `start()` -> `getCoursesReq()` -> `fetchHTML()`
> 
> In `fetchHTML()`
> 
> https://github.com/CSE-25/amrita_pyq/blob/0b8264e5354474ea1d97c800b2ecde5b11d48df4/cmd/helpers.go#L16
> 
> 
> This line prints the error first.
> But we're also carrying the `err` string from `fetchHTML` back all the way to `start()` and printing it.
> 
> Now in the output: - TWO ERROR messages but in reverse order.
> 
> ```
> Error fetching the URL. Make sure you're connected to Amrita WiFi or VPN.
> failed to fetch the HTML content
> ```
> 
> This doesn't look good to me. If we can give a cause and effect relationship to this and print properly, it will be useful. Else, we can just ignore this error message.
> 
> Or have a logger that separates `debug` and `info` level error messages to make better use of the logs.
> 
> What's your take on this @IAmRiteshKoushik and @Abhinav-ark?

I faced this issue when i tried to change Errorf to print.

**Comment by Ashrockzzz2003** [comment]
> @Ashrockzzz2003 @IAmRiteshKoushik ErrorF was used because I wanted the application to stop in case of Errors.

But return is already there to stop. But I'm sure `Errorf` did not stop execution, `return` did.
Let's try TUI
See how it goes.

**Comment by Ashrockzzz2003** [comment]
> @Ashrockzzz2003 if we are porting the application to a TUI then we can have a `diagnostics box` on the right hand side of the screen where things can be monitored constantly and error messages / success messages can be printed.
> 
> It can keep track of all events that are happening within the application and give visual updates to the user. (think of it as being similar to the chat section of a multiplayer gaming lobby - PLAYER JOINED, PLAYED LEFT, etc.)

let's try

**Comment by IAmRiteshKoushik** [comment]
Closing this PR.

**Pull request closed without merging**
